### ISSUE TITLE
Supporting ethers human-readable ABIs

### ISSUE THREAD

**Issue by koredefashokun** [Destiner/ethcall#138]
Hello. Great work on this library. It's very simple and easy to use.

I'm currently in the process of switching one of the projects I work on to using ethers' [Human Readable ABI](https://docs.ethers.io/v5/api/utils/abi/formats/#abi-formats--human-readable-abi) format, as opposed to the standard ABI format, particularly because of the readability, as well as the (minimal) bundle size savings we can get from doing that (we have a lot of ABI's in the frontend code). However, since ethcall (to my understanding) does not support this, we still have to keep the regular ABIs around for the contracts we use ethcall on.

I was wondering if adding support for this was on the roadmap. If so, I would love to open a PR that does this.

That said, I completely understand if you would like to keep this library as-is, and not introduce more complexity.

**Comment by Destiner** [comment]
Hey @koredefashokun, thanks for bringing this up!

I'm generally supporting this. Since we're using ethers under the hood, I don't think there's going to be lots of code added.

Besides, I think it's already possible to use Human Readable ABI if you first convert it to JSON format? From the [docs](https://docs.ethers.io/v5/api/utils/abi/formats/#abi-formats--converting-between-formats):

```
const iface = new Interface(humanReadableAbi);
jsonAbi = iface.format(FormatTypes.json);
```

And then you'll pass `jsonAbi` into `ethcall`. Does that make sense?

**Comment by koredefashokun** [comment]
@Destiner that makes sense. I should have thought about that. Thanks.

Again, great work on the project!

**Comment by Destiner** [comment]
Closing for now. Let me know if you'll have any issues with the above approach.
